version: '3.8'

services:
  test-postgres:
    image: postgres:latest
    container_name: test-postgres
    ports:
      - "5433:5432" # Используем другой порт, чтобы избежать конфликта с основной БД
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_segment_manager
    volumes:
      - test-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U test_user -d test_segment_manager" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  test-postgres-data: