version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: segment-manager

  service:
    build:
      context: .  # Путь к директории с Dockerfile
      dockerfile: Dockerfile  # Имя вашего Dockerfile, если отличается от "Dockerfile"
    container_name: service
    ports:
      - "8080:8080"  # Пробрасываем порт 8080 контейнера на порт 8080 хоста
    depends_on:
      - postgres

volumes:
    postgres-data:

